/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './modal.directive.component';
import * as i2 from './modal.service';
const styles_ModalComponent:any[] = ([] as any[]);
export const RenderType_ModalComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ModalComponent,data:{}});
export function View_ModalComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵncd((null as any),0)],(null as any),(null as any));
}
export function View_ModalComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'modal',([] as any[]),
      (null as any),(null as any),(null as any),View_ModalComponent_0,RenderType_ModalComponent)),
      i0.ɵdid(245760,(null as any),0,i1.ModalComponent,[i2.ModalService,i0.ElementRef],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ModalComponentNgFactory:i0.ComponentFactory<i1.ModalComponent> = i0.ɵccf('modal',
    i1.ModalComponent,View_ModalComponent_Host_0,{id:'id'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2hhcnZleWNodWkvRG9jdW1lbnRzL0NvZGluZ18yMDE3L1JvbmluRGV2UmV3b3JrL2Fzc2V0cy9hcHAvc2hhcmVkL21vZGFsLmRpcmVjdGl2ZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvaGFydmV5Y2h1aS9Eb2N1bWVudHMvQ29kaW5nXzIwMTcvUm9uaW5EZXZSZXdvcmsvYXNzZXRzL2FwcC9zaGFyZWQvbW9kYWwuZGlyZWN0aXZlLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2hhcnZleWNodWkvRG9jdW1lbnRzL0NvZGluZ18yMDE3L1JvbmluRGV2UmV3b3JrL2Fzc2V0cy9hcHAvc2hhcmVkL21vZGFsLmRpcmVjdGl2ZS5jb21wb25lbnQudHMuTW9kYWxDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2hhcnZleWNodWkvRG9jdW1lbnRzL0NvZGluZ18yMDE3L1JvbmluRGV2UmV3b3JrL2Fzc2V0cy9hcHAvc2hhcmVkL21vZGFsLmRpcmVjdGl2ZS5jb21wb25lbnQudHMuTW9kYWxDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bmctY29udGVudD48L25nLWNvbnRlbnQ+IiwiPG1vZGFsPjwvbW9kYWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OzJCQ0FBOzs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
