/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './shared/header.component.ngfactory';
import * as i2 from './shared/header.component';
import * as i3 from '@angular/router';
import * as i4 from './shared/footer.component.ngfactory';
import * as i5 from './shared/footer.component';
import * as i6 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_HeaderComponent_0,i1.RenderType_HeaderComponent)),
      i0.ɵdid(114688,(null as any),0,i2.HeaderComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(212992,
          (null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,
              i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),1,'app-footer',([] as any[]),(null as any),
              (null as any),(null as any),i4.View_FooterComponent_0,i4.RenderType_FooterComponent)),
      i0.ɵdid(49152,(null as any),0,i5.FooterComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,4,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i6.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i6.AppComponent> = i0.ɵccf('my-app',
    i6.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2hhcnZleWNodWkvRG9jdW1lbnRzL0NvZGluZ18yMDE3L1JvbmluRGV2UmV3b3JrL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9oYXJ2ZXljaHVpL0RvY3VtZW50cy9Db2RpbmdfMjAxNy9Sb25pbkRldlJld29yay9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9oYXJ2ZXljaHVpL0RvY3VtZW50cy9Db2RpbmdfMjAxNy9Sb25pbkRldlJld29yay9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2hhcnZleWNodWkvRG9jdW1lbnRzL0NvZGluZ18yMDE3L1JvbmluRGV2UmV3b3JrL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+XG48cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG48YXBwLWZvb3Rlcj48L2FwcC1mb290ZXI+XG4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUEsZUFBeUIsdUNBQ3pCO1VBQUE7VUFBQSxpRUFBQTtVQUFBOzBDQUFBO1VBQUEsNkJBQStCLHVDQUMvQjtpQkFBQTtjQUFBO2FBQUE7VUFBQSxlQUF5QjtJQUZ6QjtJQUNBOzs7O29CQ0RBO01BQUE7YUFBQTs7OzsifQ==
